spring:
  profiles: default
foo:
  list:
    - name: my name
      description: my description
---
spring:
  profiles: devH2
  activemq:
    in-memory: true
    pool:
      enabled: false
foo:
  list:
       - name: my another name H2
 
---       
spring:
  profiles: devOracle
foo:
  list:
       - name: my another name Oracle*
---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80


      